# Generated by Django 4.2.3 on 2023-07-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_app', '0003_delete_behavior_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='behavior',
            field=models.CharField(choices=[('disruption', 'Disruption'), ('disrespect', 'Disrespect'), ('tardy', 'Tardy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='behavior_app.student'),
        ),
    ]
