# Generated by Django 4.2.3 on 2023-07-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_app', '0004_alter_note_behavior_alter_note_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behavior_app.behavior'),
        ),
    ]
